/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2018-01-19 13:05:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.database.ConnectionManager;
import java.util.HashMap;
import com.beans.UserModel;
import com.helper.StringHelper;

public final class ajax_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	String sMethod = StringHelper.n2s(request.getParameter("methodId"));
	String returnString = "";
	System.out.println("HIIIII");
	boolean bypasswrite = false;
	HashMap parameters = StringHelper.displayRequest(request);
	HashMap hm = null;

	if (sMethod.equalsIgnoreCase("registerNewUser")) {
		returnString = ConnectionManager.insertUser(parameters);
		System.out.println(returnString.length());
		if (returnString.length() == 28)
			returnString = "1";
		else
			returnString = "0";
	} else if (sMethod.equalsIgnoreCase("checkLogin")) {
		UserModel um = ConnectionManager.checkLogin(parameters);
		if (um != null) {
			session.setAttribute("USER_MODEL", um);
			returnString = "1";
		} else {
			returnString = "0";
		}
	}	
	
	else if (sMethod.equalsIgnoreCase("registervehicle")) {
		UserModel um = (UserModel) session.getAttribute("USER_MODEL");
		returnString = ConnectionManager.insertVehicle(parameters,um);
		if (!returnString.equalsIgnoreCase("0")) {
			returnString = "1";
			
		} else {
			returnString = "0"; 
		}
	}else if (sMethod.equalsIgnoreCase("graph")) {
		UserModel um = (UserModel) session.getAttribute("USER_MODEL");
		String[] data = ConnectionManager.getvehiclefuelDetails3(parameters, um);
		out.println(data[0]+"_"+data[1]);
				
	}else if (sMethod.equalsIgnoreCase("logout")) {
		UserModel um1 = (UserModel) session.getAttribute("USER_MODEL");
		session.removeAttribute("USER_MODEL");
		bypasswrite = true;

      out.write("<script>\r\n");
      out.write("\t\twindow.location.href='");
      out.print(request.getContextPath());
      out.write("/pages/login.jsp';\r\n");
      out.write("\t</script>\r\n");

	}
	if (!bypasswrite) {
		out.println(returnString);
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
