/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2018-01-19 13:03:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<footer class=\"main-footer\">\r\n");
      out.write("    <div class=\"pull-right hidden-xs\">\r\n");
      out.write("      <b>Version</b> 2.4.0\r\n");
      out.write("    </div>\r\n");
      out.write("    <strong>Copyright &copy; 2017-2018 <a href=\"https://adminlte.io\">DGI</a>.</strong> All rights\r\n");
      out.write("    reserved.\r\n");
      out.write("  </footer>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Control Sidebar -->\r\n");
      out.write("<!--   <aside class=\"control-sidebar control-sidebar-dark\"> -->\r\n");
      out.write("<!--     Create the tabs -->\r\n");
      out.write("<!--     <ul class=\"nav nav-tabs nav-justified control-sidebar-tabs\"> -->\r\n");
      out.write("<!--       <li><a href=\"#control-sidebar-home-tab\" data-toggle=\"tab\"><i class=\"fa fa-home\"></i></a></li> -->\r\n");
      out.write("<!--       <li><a href=\"#control-sidebar-settings-tab\" data-toggle=\"tab\"><i class=\"fa fa-gears\"></i></a></li> -->\r\n");
      out.write("<!--     </ul> -->\r\n");
      out.write("<!--     Tab panes -->\r\n");
      out.write("<!--     <div class=\"tab-content\"> -->\r\n");
      out.write("<!--       Home tab content -->\r\n");
      out.write("<!--       <div class=\"tab-pane\" id=\"control-sidebar-home-tab\"> -->\r\n");
      out.write("<!--         <h3 class=\"control-sidebar-heading\">Recent Activity</h3> -->\r\n");
      out.write("<!--         <ul class=\"control-sidebar-menu\"> -->\r\n");
      out.write("<!--           <li> -->\r\n");
      out.write("<!--             <a href=\"javascript:void(0)\"> -->\r\n");
      out.write("<!--               <i class=\"menu-icon fa fa-birthday-cake bg-red\"></i> -->\r\n");
      out.write("\r\n");
      out.write("<!--               <div class=\"menu-info\"> -->\r\n");
      out.write("<!--                 <h4 class=\"control-sidebar-subheading\">Langdon's Birthday</h4> -->\r\n");
      out.write("\r\n");
      out.write("<!--                 <p>Will be 23 on April 24th</p> -->\r\n");
      out.write("<!--               </div> -->\r\n");
      out.write("<!--             </a> -->\r\n");
      out.write("<!--           </li> -->\r\n");
      out.write("<!--           <li> -->\r\n");
      out.write("<!--             <a href=\"javascript:void(0)\"> -->\r\n");
      out.write("<!--               <i class=\"menu-icon fa fa-user bg-yellow\"></i> -->\r\n");
      out.write("\r\n");
      out.write("<!--               <div class=\"menu-info\"> -->\r\n");
      out.write("<!--                 <h4 class=\"control-sidebar-subheading\">Frodo Updated His Profile</h4> -->\r\n");
      out.write("\r\n");
      out.write("<!--                 <p>New phone +1(800)555-1234</p> -->\r\n");
      out.write("<!--               </div> -->\r\n");
      out.write("<!--             </a> -->\r\n");
      out.write("<!--           </li> -->\r\n");
      out.write("<!--           <li> -->\r\n");
      out.write("<!--             <a href=\"javascript:void(0)\"> -->\r\n");
      out.write("<!--               <i class=\"menu-icon fa fa-envelope-o bg-light-blue\"></i> -->\r\n");
      out.write("\r\n");
      out.write("<!--               <div class=\"menu-info\"> -->\r\n");
      out.write("<!--                 <h4 class=\"control-sidebar-subheading\">Nora Joined Mailing List</h4> -->\r\n");
      out.write("\r\n");
      out.write("<!--                 <p>nora@example.com</p> -->\r\n");
      out.write("<!--               </div> -->\r\n");
      out.write("<!--             </a> -->\r\n");
      out.write("<!--           </li> -->\r\n");
      out.write("<!--           <li> -->\r\n");
      out.write("<!--             <a href=\"javascript:void(0)\"> -->\r\n");
      out.write("<!--               <i class=\"menu-icon fa fa-file-code-o bg-green\"></i> -->\r\n");
      out.write("\r\n");
      out.write("<!--               <div class=\"menu-info\"> -->\r\n");
      out.write("<!--                 <h4 class=\"control-sidebar-subheading\">Cron Job 254 Executed</h4> -->\r\n");
      out.write("\r\n");
      out.write("<!--                 <p>Execution time 5 seconds</p> -->\r\n");
      out.write("<!--               </div> -->\r\n");
      out.write("<!--             </a> -->\r\n");
      out.write("<!--           </li> -->\r\n");
      out.write("<!--         </ul> -->\r\n");
      out.write("<!--         /.control-sidebar-menu -->\r\n");
      out.write("\r\n");
      out.write("<!--         <h3 class=\"control-sidebar-heading\">Tasks Progress</h3> -->\r\n");
      out.write("<!--         <ul class=\"control-sidebar-menu\"> -->\r\n");
      out.write("<!--           <li> -->\r\n");
      out.write("<!--             <a href=\"javascript:void(0)\"> -->\r\n");
      out.write("<!--               <h4 class=\"control-sidebar-subheading\"> -->\r\n");
      out.write("<!--                 Custom Template Design -->\r\n");
      out.write("<!--                 <span class=\"label label-danger pull-right\">70%</span> -->\r\n");
      out.write("<!--               </h4> -->\r\n");
      out.write("\r\n");
      out.write("<!--               <div class=\"progress progress-xxs\"> -->\r\n");
      out.write("<!--                 <div class=\"progress-bar progress-bar-danger\" style=\"width: 70%\"></div> -->\r\n");
      out.write("<!--               </div> -->\r\n");
      out.write("<!--             </a> -->\r\n");
      out.write("<!--           </li> -->\r\n");
      out.write("<!--           <li> -->\r\n");
      out.write("<!--             <a href=\"javascript:void(0)\"> -->\r\n");
      out.write("<!--               <h4 class=\"control-sidebar-subheading\"> -->\r\n");
      out.write("<!--                 Update Resume -->\r\n");
      out.write("<!--                 <span class=\"label label-success pull-right\">95%</span> -->\r\n");
      out.write("<!--               </h4> -->\r\n");
      out.write("\r\n");
      out.write("<!--               <div class=\"progress progress-xxs\"> -->\r\n");
      out.write("<!--                 <div class=\"progress-bar progress-bar-success\" style=\"width: 95%\"></div> -->\r\n");
      out.write("<!--               </div> -->\r\n");
      out.write("<!--             </a> -->\r\n");
      out.write("<!--           </li> -->\r\n");
      out.write("<!--           <li> -->\r\n");
      out.write("<!--             <a href=\"javascript:void(0)\"> -->\r\n");
      out.write("<!--               <h4 class=\"control-sidebar-subheading\"> -->\r\n");
      out.write("<!--                 Laravel Integration -->\r\n");
      out.write("<!--                 <span class=\"label label-warning pull-right\">50%</span> -->\r\n");
      out.write("<!--               </h4> -->\r\n");
      out.write("\r\n");
      out.write("<!--               <div class=\"progress progress-xxs\"> -->\r\n");
      out.write("<!--                 <div class=\"progress-bar progress-bar-warning\" style=\"width: 50%\"></div> -->\r\n");
      out.write("<!--               </div> -->\r\n");
      out.write("<!--             </a> -->\r\n");
      out.write("<!--           </li> -->\r\n");
      out.write("<!--           <li> -->\r\n");
      out.write("<!--             <a href=\"javascript:void(0)\"> -->\r\n");
      out.write("<!--               <h4 class=\"control-sidebar-subheading\"> -->\r\n");
      out.write("<!--                 Back End Framework -->\r\n");
      out.write("<!--                 <span class=\"label label-primary pull-right\">68%</span> -->\r\n");
      out.write("<!--               </h4> -->\r\n");
      out.write("\r\n");
      out.write("<!--               <div class=\"progress progress-xxs\"> -->\r\n");
      out.write("<!--                 <div class=\"progress-bar progress-bar-primary\" style=\"width: 68%\"></div> -->\r\n");
      out.write("<!--               </div> -->\r\n");
      out.write("<!--             </a> -->\r\n");
      out.write("<!--           </li> -->\r\n");
      out.write("<!--         </ul> -->\r\n");
      out.write("<!--         /.control-sidebar-menu -->\r\n");
      out.write("\r\n");
      out.write("<!--       </div> -->\r\n");
      out.write("<!--       /.tab-pane -->\r\n");
      out.write("<!--       Stats tab content -->\r\n");
      out.write("<!--       <div class=\"tab-pane\" id=\"control-sidebar-stats-tab\">Stats Tab Content</div> -->\r\n");
      out.write("<!--       /.tab-pane -->\r\n");
      out.write("<!--       Settings tab content -->\r\n");
      out.write("<!--       <div class=\"tab-pane\" id=\"control-sidebar-settings-tab\"> -->\r\n");
      out.write("<!--         <form method=\"post\"> -->\r\n");
      out.write("<!--           <h3 class=\"control-sidebar-heading\">General Settings</h3> -->\r\n");
      out.write("\r\n");
      out.write("<!--           <div class=\"form-group\"> -->\r\n");
      out.write("<!--             <label class=\"control-sidebar-subheading\"> -->\r\n");
      out.write("<!--               Report panel usage -->\r\n");
      out.write("<!--               <input type=\"checkbox\" class=\"pull-right\" checked> -->\r\n");
      out.write("<!--             </label> -->\r\n");
      out.write("\r\n");
      out.write("<!--             <p> -->\r\n");
      out.write("<!--               Some information about this general settings option -->\r\n");
      out.write("<!--             </p> -->\r\n");
      out.write("<!--           </div> -->\r\n");
      out.write("<!--           /.form-group -->\r\n");
      out.write("\r\n");
      out.write("<!--           <div class=\"form-group\"> -->\r\n");
      out.write("<!--             <label class=\"control-sidebar-subheading\"> -->\r\n");
      out.write("<!--               Allow mail redirect -->\r\n");
      out.write("<!--               <input type=\"checkbox\" class=\"pull-right\" checked> -->\r\n");
      out.write("<!--             </label> -->\r\n");
      out.write("\r\n");
      out.write("<!--             <p> -->\r\n");
      out.write("<!--               Other sets of options are available -->\r\n");
      out.write("<!--             </p> -->\r\n");
      out.write("<!--           </div> -->\r\n");
      out.write("<!--           /.form-group -->\r\n");
      out.write("\r\n");
      out.write("<!--           <div class=\"form-group\"> -->\r\n");
      out.write("<!--             <label class=\"control-sidebar-subheading\"> -->\r\n");
      out.write("<!--               Expose author name in posts -->\r\n");
      out.write("<!--               <input type=\"checkbox\" class=\"pull-right\" checked> -->\r\n");
      out.write("<!--             </label> -->\r\n");
      out.write("\r\n");
      out.write("<!--             <p> -->\r\n");
      out.write("<!--               Allow the user to show his name in blog posts -->\r\n");
      out.write("<!--             </p> -->\r\n");
      out.write("<!--           </div> -->\r\n");
      out.write("<!--           /.form-group -->\r\n");
      out.write("\r\n");
      out.write("<!--           <h3 class=\"control-sidebar-heading\">Chat Settings</h3> -->\r\n");
      out.write("\r\n");
      out.write("<!--           <div class=\"form-group\"> -->\r\n");
      out.write("<!--             <label class=\"control-sidebar-subheading\"> -->\r\n");
      out.write("<!--               Show me as online -->\r\n");
      out.write("<!--               <input type=\"checkbox\" class=\"pull-right\" checked> -->\r\n");
      out.write("<!--             </label> -->\r\n");
      out.write("<!--           </div> -->\r\n");
      out.write("<!--           /.form-group -->\r\n");
      out.write("\r\n");
      out.write("<!--           <div class=\"form-group\"> -->\r\n");
      out.write("<!--             <label class=\"control-sidebar-subheading\"> -->\r\n");
      out.write("<!--               Turn off notifications -->\r\n");
      out.write("<!--               <input type=\"checkbox\" class=\"pull-right\"> -->\r\n");
      out.write("<!--             </label> -->\r\n");
      out.write("<!--           </div> -->\r\n");
      out.write("<!--           /.form-group -->\r\n");
      out.write("\r\n");
      out.write("<!--           <div class=\"form-group\"> -->\r\n");
      out.write("<!--             <label class=\"control-sidebar-subheading\"> -->\r\n");
      out.write("<!--               Delete chat history -->\r\n");
      out.write("<!--               <a href=\"javascript:void(0)\" class=\"text-red pull-right\"><i class=\"fa fa-trash-o\"></i></a> -->\r\n");
      out.write("<!--             </label> -->\r\n");
      out.write("<!--           </div> -->\r\n");
      out.write("<!--           /.form-group -->\r\n");
      out.write("<!--         </form> -->\r\n");
      out.write("<!--       </div> -->\r\n");
      out.write("<!--       /.tab-pane -->\r\n");
      out.write("<!--     </div> -->\r\n");
      out.write("<!--   </aside> -->\r\n");
      out.write("  <!-- /.control-sidebar -->\r\n");
      out.write("<!-- Add the sidebar's background. This div must be placed\r\n");
      out.write("       immediately after the control sidebar -->\r\n");
      out.write("  <div class=\"control-sidebar-bg\"></div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
