/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2018-01-19 13:06:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.helper.StringHelper;
import com.beans.*;
import com.database.ConnectionManager;
import java.util.*;

public final class graphs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/header_files.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hold-transition skin-blue sidebar-mini\">\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/header.jsp", out, false);
      out.write("\r\n");
      out.write("  \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/left_sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");

	HashMap hm = null;
	String lablelist1 = null;
	String lablelist2 = null;
	String data1 = null;
	String data2 = null;
// 	lablelist1 = lablelist2 = "[";
// 	data1= data2 = ("[");
	UserModel um = (UserModel) session.getAttribute("USER_MODEL");
	String userid=um.getUserid();


      out.write(" \r\n");
      out.write("  <!-- Content Wrapper. Contains page content -->\r\n");
      out.write("  <div class=\"content-wrapper\">\r\n");
      out.write("    <!-- Content Header (Page header) -->\r\n");
      out.write("    <section class=\"content-header\">\r\n");
      out.write("      <h1>Fuel Graphs </h1>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main content -->\r\n");
      out.write("    <section class=\"content\">\r\n");
      out.write("      <!-- Main row -->\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <!-- Left col -->\r\n");
      out.write("        <section class=\"col-lg-4 connectedSortable\">\r\n");
      out.write("\t\t\t<div class=\"box box-primary\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box-header with-border\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"box-title\">Vehicle</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /.box-header -->\r\n");
      out.write("\t\t\t\t\t<!-- form start -->\r\n");
      out.write("\t\t\t\t\t<form role=\"form\" name=\"myform\" id=\"myform\" action=\"javascript:fnShow();\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>Select Vehicle</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"vehicletype\" id=\"vehicletype\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Select Type</option>\r\n");

	VehicleDetails vd = null;
	List list = ConnectionManager.getvehicleDetails(userid);
	if(list.size()>0){
		for(int i=0;i<list.size();i++){
			vd = (VehicleDetails) list.get(i);

      out.write("\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(vd.getVehicleid());
      out.write('"');
      out.write('>');
      out.print(vd.getVehicletype() + " (" + vd.getVehicleno()+")");
      out.write("</option>\r\n");

		}
	}

      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>Select Graph</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"graphtype\" id=\"graphtype\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>Select Type</option>\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Petrol Filled\">Petrol Filled</option>\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"KM Driven\">KM Driven</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /.box-body -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"box-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">Show Graph</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<!-- form end -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.box -->  \t\t\r\n");
      out.write("         \r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- /.Left col -->\r\n");
      out.write("        \r\n");
      out.write("        <!-- right col (We are only adding the ID to make the widgets sortable)-->\r\n");
      out.write("        <section class=\"col-lg-8 connectedSortable\">\r\n");
      out.write("\t\t\t<div class=\"box box-solid bg-light-blue-gradient\" id=\"graphbox\" style=\"display:none;\">\r\n");
      out.write("            <div class=\"box-header ui-sortable-handle\" style=\"cursor: move;\">\r\n");
      out.write("              <i class=\"fa fa-th\"></i>\r\n");
      out.write("\r\n");
      out.write("              <h3 class=\"box-title\"><label  id=\"graphname\"></label></h3>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"box-tools pull-right\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary btn-sm pull-right\" data-widget=\"collapse\"><i class=\"fa fa-minus\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary btn-sm pull-right\" data-widget=\"remove\"><i class=\"fa fa-times\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"box-body border-radius-none\">\r\n");
      out.write("              <div class=\"chart\" id=\"line-chart\" style=\"height: 500px;\">\r\n");
      out.write("              \t<canvas id=\"canvas1\" height=\"450\" width=\"600\"></canvas>\r\n");
      out.write("              \t<canvas id=\"canvas2\" height=\"450\" width=\"600\"></canvas>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.box-body -->\r\n");
      out.write("            <!-- /.box-footer -->\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- right col -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /.row (main row) -->\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- /.content -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.content-wrapper -->\r\n");
      out.write("  \r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/footer.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("<!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../tiles/footer_files.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("function fnShow(){\r\n");
      out.write("\tvar str = $(\"#myform\" ).serialize();\r\n");
      out.write("//   \talert(str);\r\n");
      out.write("  \t\r\n");
      out.write("\tvar graphT = document.getElementById(\"graphtype\");\r\n");
      out.write("\tvar graph = graphT.options[graphT.selectedIndex].value;\t\r\n");
      out.write("\tvar vehicleT = document.getElementById(\"vehicletype\");\r\n");
      out.write("\t//var vid = vehicleT.options[vehicleT.selectedIndex].value;\r\n");
      out.write("// \talert(graphT,vid);\r\n");
      out.write("\talert(\"vehicleT\"+vehicleT.value);\r\n");
      out.write("\r\n");
      out.write("\tdocument.getElementById(\"graphname\").innerHTML = graph+ \" Graph\";\r\n");
      out.write("\tdocument.getElementById(\"graphbox\").style.display = \"block\";\r\n");
      out.write("\t\r\n");
      out.write("\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=graph\",\r\n");
      out.write("\t\t\tstr, function(data) {\r\n");
      out.write("\t\t\t\tdata = $.trim(data);\r\n");
      out.write("\t\t\t\talert(data);\r\n");
      out.write("\t\t\t\tlabels=data.split(\"_\")[0];\r\n");
      out.write("\t\t\t\tdata=data.split(\"_\")[1];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(graph == \"Petrol Filled\"){\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"canvas1\").style.display = \"block\";\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"canvas2\").style.display = \"none\";\r\n");
      out.write("\t\t\t\t\tgraph1(labels.split(','),data.split(','));\r\n");
      out.write("\t\t\t\t}else if(graph == \"KM Driven\"){\t\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"canvas1\").style.display = \"none\";\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"canvas2\").style.display = \"block\";\r\n");
      out.write("\t\t\t\t\tgraph2(labels.split(','),data.split(','));\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function graph1(labelsData,axisData){\r\n");
      out.write("\tvar lineChartData = {\r\n");
      out.write("\t\tlabels :labelsData,\r\n");
      out.write("\t\tdatasets : [\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tlabel: \"My First dataset\",\r\n");
      out.write("\t\t\t\tfillColor : \"rgba(220,220,220,0.2)\",\r\n");
      out.write("\t\t\t\tstrokeColor : \"rgba(220,220,220,1)\", \r\n");
      out.write("\t\t\t\tpointColor : \"rgba(220,220,220,1)\",\r\n");
      out.write("\t\t\t\tpointStrokeColor : \"#fff\",\r\n");
      out.write("\t\t\t\tpointHighlightFill : \"rgba(0,0,0,0)\",\r\n");
      out.write("\t\t\t\tpointHighlightStroke : \"rgba(220,220,220,1)\",\r\n");
      out.write("\t\t\t\tdata :axisData\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t]\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar ctx = document.getElementById(\"canvas1\").getContext(\"2d\");\r\n");
      out.write("\twindow.myLine = new Chart(ctx).Line(lineChartData, {\r\n");
      out.write("\t\tresponsive: true\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function graph2(labelsData,axisData){\r\n");
      out.write("\tvar lineChartData = {\r\n");
      out.write("\t\tlabels :labelsData,\r\n");
      out.write("\t\tdatasets : [\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tlabel: \"My First dataset\",\r\n");
      out.write("\t\t\t\tfillColor : \"rgba(220,220,220,0.2)\",\r\n");
      out.write("\t\t\t\tstrokeColor : \"rgba(220,220,220,1)\", \r\n");
      out.write("\t\t\t\tpointColor : \"rgba(220,220,220,1)\",\r\n");
      out.write("\t\t\t\tpointStrokeColor : \"#fff\",\r\n");
      out.write("\t\t\t\tpointHighlightFill : \"rgba(0,0,0,0)\",\r\n");
      out.write("\t\t\t\tpointHighlightStroke : \"rgba(220,220,220,1)\",\r\n");
      out.write("\t\t\t\tdata :axisData\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t]\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar ctx = document.getElementById(\"canvas2\").getContext(\"2d\");\r\n");
      out.write("\twindow.myLine = new Chart(ctx).Line(lineChartData, {\r\n");
      out.write("\t\tresponsive: true\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
